### ISSUE TITLE
ARM 无法运行

### ISSUE THREAD

**Issue by lloyd18** [smartping/smartping#106]
有个 arm vps， 系统是 debian12，运行 ./control start 提示运行成功，但 ./control status 是 stop状态

**Comment by lloyd18** [comment]
自己编译吧。

**Comment by mx4994** [comment]
你编译成功了嘛？我提示这个不知道怎么弄
```
go: go.mod file not found in current directory or any parent directory.                                                         'go get' is no longer supported outside a module.
        To build and install a command, use 'go install' with a version,
        like 'go install example.com/cmd@latest'                                                                                For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
src/smartping.go:6:2: no required module provides package github.com/jakecoffman/cron: go.mod file not found in current directory or any parent directory; see 'go help modules'
src/smartping.go:7:2: no required module provides package github.com/smartping/smartping/src/funcs: go.mod file not found in current directory or any parent directory; see 'go help modules'
src/smartping.go:8:2: no required module provides package github.com/smartping/smartping/src/g: go.mod file not found in current directory or any parent directory; see 'go help modules'
src/smartping.go:9:2: no required module provides package github.com/smartping/smartping/src/http: go.mod file not found in current directory or any parent directory; see 'go help modules'
```

**Comment by lloyd18** [comment]
> 你编译成功了嘛？我提示这个不知道怎么弄
> 
> ```
> go: go.mod file not found in current directory or any parent directory.                                                         'go get' is no longer supported outside a module.
>         To build and install a command, use 'go install' with a version,
>         like 'go install example.com/cmd@latest'                                                                                For more information, see https://golang.org/doc/go-get-install-deprecation
>         or run 'go help get' or 'go help install'.
> src/smartping.go:6:2: no required module provides package github.com/jakecoffman/cron: go.mod file not found in current directory or any parent directory; see 'go help modules'
> src/smartping.go:7:2: no required module provides package github.com/smartping/smartping/src/funcs: go.mod file not found in current directory or any parent directory; see 'go help modules'
> src/smartping.go:8:2: no required module provides package github.com/smartping/smartping/src/g: go.mod file not found in current directory or any parent directory; see 'go help modules'
> src/smartping.go:9:2: no required module provides package github.com/smartping/smartping/src/http: go.mod file not found in current directory or any parent directory; see 'go help modules'
> ```

成功过，但现在不用了，问问 gpt

**Comment by mx4994** [comment]
> > 你编译成功了嘛？我提示这个不知道怎么弄
> > ```
> > go: go.mod file not found in current directory or any parent directory.                                                         'go get' is no longer supported outside a module.
> >         To build and install a command, use 'go install' with a version,
> >         like 'go install example.com/cmd@latest'                                                                                For more information, see https://golang.org/doc/go-get-install-deprecation
> >         or run 'go help get' or 'go help install'.
> > src/smartping.go:6:2: no required module provides package github.com/jakecoffman/cron: go.mod file not found in current directory or any parent directory; see 'go help modules'
> > src/smartping.go:7:2: no required module provides package github.com/smartping/smartping/src/funcs: go.mod file not found in current directory or any parent directory; see 'go help modules'
> > src/smartping.go:8:2: no required module provides package github.com/smartping/smartping/src/g: go.mod file not found in current directory or any parent directory; see 'go help modules'
> > src/smartping.go:9:2: no required module provides package github.com/smartping/smartping/src/http: go.mod file not found in current directory or any parent directory; see 'go help modules'
> > ```
> 
> 成功过，但现在不用了，问问 gpt

感谢回复，已经解决用上了。下面是解决方法
```
go mod init get
go get github.com/jakecoffman/cron
go get github.com/smartping/smartping/src/funcs
go get github.com/smartping/smartping/src/g
go get github.com/smartping/smartping/src/http
```
