### ISSUE TITLE
ping的频率的问题

### ISSUE THREAD

**Issue by kikiyou** [smartping/smartping#12]
cmd := exec.Command("ping", "-w", "5", "-c", cnt, Addr)
cnt 默认是 10
默认的linux ping的参数是：
ping -w 5 -c 10
因为 -w 超时是5 秒，ping的默认间隔是1秒一个包，这样只会每次发5个包，每次检测每分钟前5秒包质量
建议改为：
ping -w 60 -i 6 -c  10
这样每6秒发一次包，发10次,这样能检测每分钟的网络质量

**Comment by toryzen** [comment]
:thumbsup: 这个参数确实有问题 下个版本准备不再使用系统的ping命令 我再测试一下近期一块更新
