### ISSUE TITLE
Reverse ping 没有数据

### ISSUE THREAD

**Issue by avyou** [smartping/smartping#15]
你好，我每个节点都部署为 CS TYPE， Topology  和 Forward ping 是正常的，但 Reverse ping 没有数据，另外 api 接口的 ping.json 数据返回都为0
`{"avgdelay":["0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0"],"lastcheck":["2017-09-19 08:58","2017-09-19 08:59","2017-09-19 09:00","2017-09-19 09:01","2017-09-19 09:02","2017-09-19 09:03","2017-09-19 09:04","2017-09-19 09:05","2017-09-19 09:06","2017-09-19 09:07","2017-09-19 09:08","2017-09-19 09:09","2017-09-19 09:10","2017-09-19 09:11","2017-09-19 09:12","2017-09-19 09:13","2017-09-19 09:14","2017-09-19 09:15","2017-09-19 09:16","2017-09-19 09:17","2017-09-19 09:18","2017-09-19 09:19","2017-09-19 09:20","2017-09-19 09:21","2017-09-19 09:22","2017-09-19 09:23","2017-09-19 09:24","2017-09-19 09:25","2017-09-19 09:26","2017-09-19 09:27","2017-09-19 09:28","2017-09-19 09:29","2017-09-19 09:30","2017-09-19 09:31","2017-09-19 09:32","2017-09-19 09:33","2017-09-19 09:34","2017-09-19 09:35","2017-09-19 09:36","2017-09-19 09:37","2017-09-19 09:38","2017-09-19 09:39","2017-09-19 09:40","2017-09-19 09:41","2017-09-19 09:42","2017-09-19 09:43","2017-09-19 09:44","2017-09-19 09:45","2017-09-19 09:46","2017-09-19 09:47","2017-09-19 09:48","2017-09-19 09:49","2017-09-19 09:50","2017-09-19 09:51","2017-09-19 09:52","2017-09-19 09:53","2017-09-19 09:54","2017-09-19 09:55","2017-09-19 09:56","2017-09-19 09:57","2017-09-19 09:58","2017-09-19 09:59","2017-09-19 10:00","2017-09-19 10:01","2017-09-19 10:02","2017-09-19 10:03","2017-09-19 10:04","2017-09-19 10:05","2017-09-19 10:06","2017-09-19 10:07","2017-09-19 10:08","2017-09-19 10:09","2017-09-19 10:10","2017-09-19 10:11","2017-09-19 10:12","2017-09-19 10:13","2017-09-19 10:14","2017-09-19 10:15","2017-09-19 10:16","2017-09-19 10:17","2017-09-19 10:18","2017-09-19 10:19","2017-09-19 10:20","2017-09-19 10:21","2017-09-19 10:22","2017-09-19 10:23","2017-09-19 10:24","2017-09-19 10:25","2017-09-19 10:26","2017-09-19 10:27","2017-09-19 10:28","2017-09-19 10:29","2017-09-19 10:30","2017-09-19 10:31","2017-09-19 10:32","2017-09-19 10:33","2017-09-19 10:34","2017-09-19 10:35","2017-09-19 10:36","2017-09-19 10:37","2017-09-19 10:38","2017-09-19 10:39","2017-09-19 10:40","2017-09-19 10:41","2017-09-19 10:42","2017-09-19 10:43","2017-09-19 10:44","2017-09-19 10:45","2017-09-19 10:46","2017-09-19 10:47","2017-09-19 10:48","2017-09-19 10:49","2017-09-19 10:50","2017-09-19 10:51","2017-09-19 10:52","2017-09-19 10:53","2017-09-19 10:54","2017-09-19 10:55","2017-09-19 10:56","2017-09-19 10:57","2017-09-19 10:58"],"losspk":["0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0"],"maxdelay":["0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0"],"mindelay":["0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0"],"revcpk":["0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0"],"sendpk":["0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0"]}`

**Comment by toryzen** [comment]
CS模式需要在每台机器上都部署smartping

**Comment by toryzen** [comment]
还有数据需要运行完后1分钟后开始生成

**Comment by cell13** [comment]
需要修改base configuration里面的 agent ip，不能是127.0.0.1，这样可以实现reverse ping

**Comment by avyou** [comment]
@toryzen有配的，我每一台都是 CS ,相同的配置，相同的密码。
@cell13 是 agent ip 的问题，修改为外网IP后解决了.
thanks!
