### ISSUE TITLE
报警是否可以支持im的方式

### ISSUE THREAD

**Issue by lyonliquid** [smartping/smartping#16]
目前报警是在系统内播放声音的方式
是否可以支持sms或者im的方式发送通知

**Comment by toryzen** [comment]
这个在考虑的计划中，最优选的IM是微信，但是只能是企业微信，这个会在后期实现。

**Comment by lyonliquid** [comment]
是否可以采用钉钉呢，open.dingtalk.com，自定义机器人的报警方式实现起来可能比较简单

**Comment by Tinet-AaronAn** [comment]
钉钉对接用http接口就可以，只要开放http回调就ok

**Comment by FanhuaCloud** [comment]
可以采用第三方微信推送 由客户配置参数：
http://sc.ftqq.com/3.version

**Comment by lizhongnian** [comment]
建议可以用邮件提醒，这样底线会降低一些，个人站长也可以使用

**Comment by cnlyzy** [comment]
我利用空余时间写了个**报警邮件提醒**  有需要的可以 [点击这里](https://github.com/cnlyzy/SmartPingMonitorSystem) 下载使用，欢迎star

**Comment by toryzen** [comment]
v0.8.0 release 增加邮件报警功能
