### ISSUE TITLE
我竟然没有配通

### ISSUE THREAD

**Issue by hongfeioo** [smartping/smartping#21]
我的场景是这样的
1    A机器10.1.0.1和B机器10.2.0.1在同一个内网环境，可以互ping通,  但都不能访问外网；
2    A启动smartping ， agentip： 10.1.0.1  ;  agentlist :本机10.1.0.1 CS,  B 机器 10.2.0.1 ，CS
      B启动smartping，   agentip： 10.2.0.1  ;  agentlist :本机10.2.0.1 CS,  A机器 10.1.0.1 ，CS
3   现象是拓扑中，本机是绿色， 一条绿线指向对方，对方是红色 
     请问对方为什么是红色呢？   

期待回复

**Comment by toryzen** [comment]
你的个人机都可以访问这两台机器吧？每台机器的agentlist都把自己也加上。

**Comment by hongfeioo** [comment]
我是可以访问AB两台机器的， 页面都能打开。  每台机器的agentlist 也加了自己

**Comment by hongfeioo** [comment]
咱们有官方的QQ群么，可否提供一下，方便交流。

**Comment by toryzen** [comment]
@hongfeioo Q群：457092442
