### ISSUE TITLE
新版本可以增加对win32平台的支持吗

### ISSUE THREAD

**Issue by givengenius** [smartping/smartping#22]

**Comment by toryzen** [comment]
可以在win32平台跑，需要自己编译一下。

**Comment by givengenius** [comment]
不太懂go，control.cmd build尝试编译，但是没成功啊

**Comment by eastFu** [comment]
我编译了一份win 32的，老弟你试试看行不行 ~ @givengenius 
  https://pan.baidu.com/s/1mionyGS

**Comment by givengenius** [comment]
@eastFu 谢谢，不过版本又更新了，我还是自己研究研究。
