### ISSUE TITLE
关于告警alert的问题

### ISSUE THREAD

**Issue by yuedingwangji** [smartping/smartping#27]
我在公网找了10台机器部署  配置
"Type": "CS",
"Thdchecksec": 900,
"Thdoccnum": 1,
"Thdavgdelay": 120,
"Thdloss": 1
可我发现 alert 里面 一大堆 告警 信息， 而且告警信息，就显示 ，from 本机 to 远程 ，
这么多告警信息，是我本机网络有问题？

**Comment by toryzen** [comment]
如果找公网的机器应该选用Type:C模式，还有确定一下在900s内有没有出现过1次延迟超过120s，丢包大于120ms的情况。

**Comment by yuedingwangji** [comment]
type:cs  不可以么， 我这些机器都部署了 smartping，配置都是一样的， 我打算服务器之间做CS， 然后在做到3个运营商IP 的  C

**Comment by yuedingwangji** [comment]
对了，"Thdchecksec": 900 这里配置900 是指在900s内一直发包么？，还是说程序还是每一分钟检测一次（检测一次发多少包？），然后到900s 就统计这900s内的发包情况，如果有延迟大于120的就告警？
或者丢包超过1个，或者丢包率高于1%就告警？

**Comment by toryzen** [comment]
CS模式是对的，我理解错你的场景了。
我又看了下的你规则，是在900s内存在1次延迟大于200，丢包大于1%即报警。报警是每分钟进行一次检测，检测时间范围为当前时间向前推900s，也就意味着如果发生了一次报警，这次报警至少会显示持续900s钟。
PING的周期为每3s发送一个PING包，1分钟发送20个。

**Comment by yuedingwangji** [comment]
还是有点不太理解 每分钟进行一次检测，检测时间范围为当前时间向前推900s，也就意味着如果发生了一次报警，这次报警至少会显示持续900s钟。 
 意思是说 1分钟发送20个ping包，每3s 发送一次ping包，如果期间丢包率大于1% 即报警？ 
本次报警持续900s ，不太理解

**Comment by toryzen** [comment]
**报警规则为：**
在Thdchecksec秒钟内出现Thdoccnum次延迟大于Thdavgdelay或丢包高于Thdloss则报警。
根据你的配置，在900秒钟内出现1次延迟高于120ms或丢包大于1%则报警。

**报警每分钟进行一次检测**

https://docs.smartping.org/install/config.html
