### ISSUE TITLE
ping值图不出

### ISSUE THREAD

**Issue by alex1528** [smartping/smartping#3]
是有依赖的相关安装包?

**Comment by toryzen** [comment]
刚才回复看错项目了，Sorry，启动后访问http://127.0.0.1:8899 看不到WEB界面么？

**Comment by alex1528** [comment]
web界面是正常的 只是没有这样的图
<img width="676" alt="default" src="https://user-images.githubusercontent.com/12593499/27891212-17136d10-622b-11e7-8be4-6911dc8ffadd.png">
拓补图是正常的

**Comment by alex1528** [comment]
拓补图右边的ping值图也没有

**Comment by toryzen** [comment]
拓补图右边的ping值图只有当报警的时候才会出现，如果配置了声音同时还会有声音报警。

**Comment by alex1528** [comment]
为什么关闭了? 首页的ping值图 也没有啊?
<img width="1224" alt="default" src="https://user-images.githubusercontent.com/12593499/27896150-a45dae1e-624a-11e7-9c0a-0c577ee49755.png">
