### ISSUE TITLE
请问如何做一个web console的proxy

### ISSUE THREAD

**Issue by Nidhoggur1993** [smartping/smartping#31]
现在有服务器ABC，都只有INPUT的防火墙
情况：
A的8899不做任何限制，BC的8899仅允许A来访问
结果：
在A上访问localhost:8899一切正常，
但是通过别的机器D访问A:8899时，reserve ping和拓扑图都不能正常显示

请问该如何设置？

**Comment by toryzen** [comment]
开启互通需要开启机器间ICMP协议与8899端口，除此之外 还需要开通自己的机器到所有服务器的8899端口互通权限
