### ISSUE TITLE
首页的ping值图不显示

### ISSUE THREAD

**Issue by alex1528** [smartping/smartping#4]
<img width="1224" alt="default" src="https://user-images.githubusercontent.com/12593499/27896179-da934944-624a-11e7-8da0-287eae8778f2.png">

**Comment by toryzen** [comment]
你把配置文件中Targets->Name中包含中杠换成下杠，utn-sh-1 换成 utn_sh_1 ，是个ＢＵＧ，抽空修复一下。

**Comment by alex1528** [comment]
good!
