### ISSUE TITLE
配置文件和api接口数据不一致

### ISSUE THREAD

**Issue by inxming** [smartping/smartping#40]
smatrping：0.4.1
system：CentOS6.5

配置文件的数据更新之后，通过request.get("http://localhost:8899/api/config.json")上获取的数据是历史数据,重启smartping服务也无法解决?

**Comment by inxming** [comment]
启动脚本有问题 无法结束进程导致。

**Comment by toryzen** [comment]
意思是无法结束进程导致API与配置文件不一致？
