### ISSUE TITLE
能不能实现个mtr功能呢

### ISSUE THREAD

**Issue by qooke** [smartping/smartping#44]
感觉mtr功能会比traceroute好用，当报警时进行mtr绘制一个路由图，这样一看就知道在哪个点上丢的包。要是在增加个当IP丢包告警调用mtr命令绘制成一个路由图文本并发送到邮件就完美了啦。

**Comment by babyfenei** [comment]
这个功能很重要·！

**Comment by ruochen** [comment]
+1

**Comment by toryzen** [comment]
v0.8.0 release , 报警记录挪至Ping拓扑节点，并将traceroute功能变更为mtr ,支持邮件
