### ISSUE TITLE
Centos6.10 普通用户运行smartping引发panic

### ISSUE THREAD

**Issue by cuiketing** [smartping/smartping#47]
![image](https://user-images.githubusercontent.com/8736134/47984027-43eafc80-e110-11e8-921e-5438fdcc7d31.png)

**Comment by toryzen** [comment]
需要root权限

**Comment by cuiketing** [comment]
内部有要求，不能使用root运行，能否通过调整代码实现普通用户运行，可以给个方向吗？

**Comment by cuiketing** [comment]
知道原因了，因为ipv4:icmp属于原始socket，必须使用root才可以。
