### ISSUE TITLE
如何更改数据默认的保留时长？

### ISSUE THREAD

**Issue by MxdStudio** [smartping/smartping#48]
您好，想问一下如何将默认数据保存时间的1个月更改为想要的时间？比如我查看6个月的网络情况，如何修改？是否可以在配置文件中增加相应的控制项以便自定义保留时长？

另，目前界面展示是一行3个站点，如果上面说的，能够调整数据时长的话，假如保留的时长比较长，那么现有展示布局来展示图标就不太好看了，最好能够添加一个更改展示布局的功能或选线，比如能够切换成一行只显示1个站点

以上，是个人的一些建议和想法，谢谢

**Comment by toryzen** [comment]
第一个问题 目前这一版本是不能修改数据保存时间的，新版本在Cloud分支上的已经支持自定义保留时间了，我们内部已经用了几个月了，年前会合并到主分支。
第二个问题 没有看明白。

**Comment by MxdStudio** [comment]
感谢回复
第二个问题和第一个有关
第二个问题的意思是，如果支持自定义保留时间可以的话，以半年为例
假如我设定了保留半年的数据，那么这个数据保留时间就变长了，现在的界面布局，显示图的x轴，宽度比较窄，如果用来显示半年的数据，那么就会比较挤
我的意思是，界面布局能否可以切换是九宫格（现在的样子，说的不准确，类似九宫格）或一行一个节点的布局，这样切换成一行一个节点来显示，对于显示半年的数据的会好一些

详见图片（画笔改的，凑合看就行，感谢）：
https://i.loli.net/2019/01/03/5c2d8dbd9695d.png

**Comment by toryzen** [comment]
v0.8.0  release 可以支持设置保存时间
