### ISSUE TITLE
boltdb分支 数据查询的起止时间跨[月]时数据出错

### ISSUE THREAD

**Issue by yuko1225** [smartping/smartping#49]
使用boltdb的分支(task和boltdb)，调用/api/ping.json的起始日期和结束日期跨越[月]单位时，返回数据会出现异常。
例如starttime=2018-12-31 23:59&endtime=2019-01-08 00:00。此时返回的json内avgdelay,losspk,maxdelay,mindelay数据全为0，只有lastcheck有正常日期。但starttime=2019-01-01 00:00结束日期不变时，返回数据则正常。日志没有报错

使用sqlite的分支没有这问题。不过sqlite分支ping目标增多后查询经常卡死，因此弃用
订正：跨[月]单位即出错

**Comment by yuko1225** [comment]
定位到问题根源了
smartping存储数据时，把日期里的[年]-[月]去掉，只保留了[日] [时]:[分]作为键。这样存储新数据时就自动覆写了上个月的老数据，也就不需要主动回收旧数据。

这个做法在sqlite没有问题，关系数据库可以存储多项数据，smartping同时在单独的列存储了[完整时间]，查询数据以[完整时间]进行查询就避免了BUG。而boltdb是K/V数据库，只能有一个键名和键值对应，此时再用去掉了[年][月]的时间作键名显然不妥

因为对Go不熟，只能提点建议
1.boltdb键名改用完整的时间格式，最好用时间戳。
2.像alert数据库那样，定期主动回收旧数据，而不是被动的数据覆写

add细节:
https://github.com/smartping/smartping/blob/4342cff1502f810992fcdbb9aeb012189b3646c7/src/http/api.go#L124-L126
因为忽略了年和月，当起始日期的[日]大于终止日期的[日]（跨月中很常见的情况），这个时段检索循环就无法正确执行

**Comment by toryzen** [comment]
目前除master分支外，task分支目前是最新的可以稳定运行的，其他的都有一些问题，同样使用boltdb存储。

**Comment by yuko1225** [comment]
> 
> 
> 目前除master分支外，task分支目前是最新的可以稳定运行的，其他的都有一些问题，同样使用boltdb存储。

感谢回复，不过这个问题在task分支亦存在。临时解决方法就是去掉
https://github.com/smartping/smartping/blob/4342cff1502f810992fcdbb9aeb012189b3646c7/src/http/api.go#L124-L126

https://github.com/smartping/smartping/blob/4342cff1502f810992fcdbb9aeb012189b3646c7/src/funcs/ping.go#L95

https://github.com/smartping/smartping/blob/4342cff1502f810992fcdbb9aeb012189b3646c7/src/funcs/alert.go#L86-L87
的[8:]。但这样的话，被动的ping旧数据回收机制就不复存在了，必须要改为主动的数据清理

**Comment by lunzima** [comment]
按照@yuko1225的做法，需要每天在空闲时段遍历一次数据库并删除过期的条目。

**Comment by toryzen** [comment]
v0.8.0 release
