### ISSUE TITLE
有没有办法支持多系统版本?

### ISSUE THREAD

**Issue by alex1528** [smartping/smartping#5]
现在只能支持glibc>2.14的,像比较老的centos6 已经不能支持了

**Comment by toryzen** [comment]
新版本在开发，预计再过一周吧，下个版本发布的时候我看下兼容问题。

**Comment by alex1528** [comment]
顺便问下,能否实现增加个api, 实现将异常情况吐給 falcon-plus中的agent组件?

**Comment by toryzen** [comment]
可以 falcon-plus没研究过，它前一个版本看过，记得是HTTP吐数据，等会看下falcon-plus的有没有变化，我们这边没用falcon，实现功能后你帮忙测下吧。

**Comment by alex1528** [comment]
厉害! 可以帮忙测试

**Comment by alex1528** [comment]
falcon-plus中的agent功能没啥大的变化, 一样是接收push上来的数据

**Comment by dagen123** [comment]
配置文件里name字段不支持‘-‘ （横杠）

**Comment by toryzen** [comment]
@dagen123  刚刚发了一个0.2.5,主要是修复这个问题

**Comment by dagen123** [comment]
🐮




发自网易邮箱大师


在2017年9月12日 20:42，toryzen<notifications@github.com> 写道：

@dagen123 刚刚发了一个0.2.5,主要是修复这个问题

**Comment by dagen123** [comment]
请教下，如何生成拓扑示例图？安装完成后是


发自网易邮箱大师


在2017年9月12日 20:42，toryzen<notifications@github.com> 写道：

@dagen123 刚刚发了一个0.2.5,主要是修复这个问题

**Comment by toryzen** [comment]
右上角有个黄色的按钮 ALTER , 点击后出来拓扑
