### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by YuanDdQiao** [smartping/smartping#6]
hello ,I'm going to build that is ok.
>smartping.exe -f ./config.json
but run in windows cmd return error:

2017/07/26 11:57:59 Opening config file:  ./config.json
2017/07/26 11:57:59 Config loaded
2017/07/26 11:57:59 starting runPingTest  本机
2017/07/26 11:57:59 starting to listen on  :8899
2017/07/26 11:57:59 starting runPingTest  NOPING
2017/07/26 11:57:59 starting runPingTest  IP_10_0_0_51
2017/07/26 11:57:59 starting runPingTest  IP_10_0_15_1
2017/07/26 11:57:59 Get status on http://localhost:8899/status
2017/07/26 11:58:03 Addr:127.0.0.1 SendPk:5 RevcPk:0 LossPk:0 | MinDelay:0 AvgDelay:0 MaxDelay:0
2017/07/26 11:58:03 REPLACE INTO pinglog  26 11:58 127.0.0.1 本机 0 0 0 5 5 0 2017-07-26 11:58
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x4d0f2d]

goroutine 20 [running]:
database/sql.(*Stmt).ExecContext(0x0, 0x97ef40, 0x119721a4, 0x11999eac, 0xa, 0xa, 0x0, 0x0, 0x0, 0x0)
        C:/Go/src/database/sql/sql.go:1789 +0x3d
database/sql.(*Stmt).Exec(0x0, 0x11999eac, 0xa, 0xa, 0x97ce90, 0x11a5b070, 0x11a5b060, 0x8)
        C:/Go/src/database/sql/sql.go:1814 +0x4d
smartping/src/funcs.runPingTest(0x11aa95c0, 0x756b63, 0x5, 0x11a5aae0, 0x9, 0x11a5aaf0, 0x9, 0x11aadda0, 0x20, 0x11aae870, ...)
        D:/goworkpath/src/smartping/src/funcs/cron.go:28 +0x7ad
created by smartping/src/funcs.StartPing
        D:/goworkpath/src/smartping/src/funcs/cron.go:13 +0x6b

Can i get some help for.?

**Comment by toryzen** [comment]
master分支？

**Comment by YuanDdQiao** [comment]
对呀，只有master 可以下载吧。？

**Comment by toryzen** [comment]
你执行 ./control start 进行启动

**Comment by YuanDdQiao** [comment]
然而不能成功。看了里面的内容，一样是启动，但是，最终问题还是smartping.exe 的问题哦。

**Comment by toryzen** [comment]
smartping的文件路径里不要出现中文，刚才试了一下，如果文件路径存在中文就有这个问题，回头我修复一下
